name: Issue Report
description: File an issue
title: "Issue: "
body:
  - type: checkboxes
    id: triedupdate
    attributes:
      options:
        - label: "**Before reporting an issue**, have you tried to force update the mod
            using Mod Updater?"
          required: true
  - type: textarea
    id: mod
    attributes:
      label: Failing mod
      description: Which mod is failing? If this is a PLib issue, specify which PLib library you believe has the issue
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Issue description
      description: Tell us what should happen and what happens instead of the expected behavior
  - type: markdown
    attributes:
      value: |
        Please also attach the full output log to allow us to understand your
        issue. This file is located at:


        Windows: `%userprofile%\AppData\LocalLow\Klei\Oxygen Not Included\Player.log`

        Mac: `~/Library/Logs/Unity/Player.log`

        Linux: `~/.config/unity3d/Klei/Oxygen Not Included/Player.log`
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How can this issue be reproduced?
  - type: checkboxes
    id: dlcs
    attributes:
      description: Which DLCs are active?
      options:
        - label: Spaced Out
        - label: Frosty Planet Pack
        - label: Bionic Booster Pack
  - type: dropdown
    id: store
    attributes:
      label: Game Platform
      description: On which store was the game purchased?
      options:
        - Steam
        - Epic
        - WeGame
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: On what operating systems/platforms does the problem occur?
      multiple: true
      options:
        - Windows
        - Mac
