/*
 * Copyright 2019 Peter Han
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

namespace PeterHan.PLib {
	/// <summary>
	/// Represents a single key binding.
	/// </summary>
	public sealed class PKeyBinding {
		/// <summary>
		/// Replaces the hotkey placeholder in a UI string with the actual key binding.
		/// </summary>
		/// <param name="template">The string template.</param>
		/// <param name="binding">The current key binding.</param>
		/// <returns>The string with the localized hot key substituted in.</returns>
		public static string ReplaceHotkeyString(string template, PKeyBinding binding) {
			return template.Replace("{Hotkey}", (binding == null || binding.Key ==
				KKeyCode.None) ? string.Empty : STRINGS.UI.FormatAsHotkey("[" + binding.
				GetBindingText() + "]"));
		}

		/// <summary>
		/// The gamepad button to bind.
		/// </summary>
		public GamepadButton GamePadButton { get; set; }

		/// <summary>
		/// The key code.
		/// </summary>
		public KKeyCode Key { get; set; }

		/// <summary>
		/// The modifier code.
		/// </summary>
		public Modifier Modifiers { get; set; }

		public PKeyBinding(KKeyCode keyCode = KKeyCode.None, Modifier modifiers = Modifier.
				None, GamepadButton gamePadButton = GamepadButton.NumButtons) {
			GamePadButton = gamePadButton;
			Key = keyCode;
			Modifiers = modifiers;
		}

		public PKeyBinding(PKeyBinding other) : this() {
			if (other != null) {
				GamePadButton = other.GamePadButton;
				Key = other.Key;
				Modifiers = other.Modifiers;
			}
		}

		public override bool Equals(object obj) {
			return obj is PKeyBinding other && other.Key == Key && other.Modifiers ==
				Modifiers && other.GamePadButton == GamePadButton;
		}

		/// <summary>
		/// Looks for duplicate key bindings in the core game bindings.
		/// </summary>
		/// <param name="newBinding">The key binding to check.</param>
		/// <returns>default(BindingEntry) if no conflicts, or the conflicting key bind otherwise.</returns>
		internal BindingEntry FindKleiDuplicateBinding() {
			// Category and action are irrelevant here
			var kleiBinding = new BindingEntry(KeyUtils.CATEGORY, GamePadButton, Key,
				Modifiers, Action.Invalid);
			var result = default(BindingEntry);
			foreach (var entry in GameInputMapping.KeyBindings)
				if (entry.IsBindingEqual(kleiBinding) && !entry.mIgnoreRootConflics) {
					result = entry;
					break;
				}
			return result;
		}

		public override int GetHashCode() {
			// Was auto generated by VS, please don't kill me
			int hashCode = 1488379021 + GamePadButton.GetHashCode();
			hashCode = hashCode * -1521134295 + Key.GetHashCode();
			hashCode = hashCode * -1521134295 + Modifiers.GetHashCode();
			return hashCode;
		}

		/// <summary>
		/// Retrieves the binding text for this key binding.
		/// </summary>
		/// <returns>A user friendly representation of the key binding.</returns>
		public string GetBindingText() {
			var code = Key;
			string text = GameUtil.GetKeycodeLocalized(code);
			if (code != KKeyCode.LeftAlt && code != KKeyCode.RightAlt && code != KKeyCode.
					LeftControl && code != KKeyCode.RightControl && code != KKeyCode.
					LeftShift && code != KKeyCode.RightShift)
				text += KeyUtils.GetModifierString(Modifiers);
			return text;
		}

		public override string ToString() {
			return GetBindingText();
		}
	}
}
